kind: pipeline
type: docker
name: default

steps:
  - name: publish_branch
    image: plugins/docker
    settings:
      repo: wuhanchu/user_auth
      tags:
        - latest
        - ${DRONE_BRANCH}
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        include: [master] # 只在 master 分支上运行
      event:
        include: [push] # 只包括 push 事件

  - name: publish_tag
    image: plugins/docker
    settings:
      repo: wuhanchu/user_auth
      tags:
        - latest
        - ${DRONE_TAG}
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        include: [master] # 只在 master 分支上运行
      event:
        include: [tag] # 只包括 tag 事件

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      port:
        from_secret: deploy_port
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_key
      script:
        - cd /home/wuhanchu/project/maintenance_script
        - ./script/check_clash.sh

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
